## Polinomial features

In [19]:
import numpy as np
from IPython.display import HTML, display
from sklearn.preprocessing import PolynomialFeatures

def imprimirTabla (data):
    display(HTML(
       '<center><table><tr>{}</tr></table></center>'.format(
           '</tr><tr>'.join(
               '<td>{}</td>'.format('</td><td>'.join(str('%.2f'%(_)) for _ in row)) for row in data)
           )
    ))

#Creación de un array 
x = np.random.rand(5,1)
print("Tensor de entrada")
print(x)


#Polinomio de grado 3
poly = PolynomialFeatures(3)
p=poly.fit_transform(x)
print("Características polinómicas de grado 3, para una dimensión")
imprimirTabla(p)




#Creación de un array bidimensional
x = np.random.rand(5,2)
print("Tensor de entrada")
print(x)


#Polinomio de grado 3
poly = PolynomialFeatures(3)
p=poly.fit_transform(x)
print("Características polinómicas de grado 3, para dos dimensiones")
imprimirTabla(p)




#Creación de un array tridimensional
x = np.random.rand(5,3)
print("Tensor de entrada")
print(x)


#Polinomio de grado 3
poly = PolynomialFeatures(3)
p=poly.fit_transform(x)
print("Características polinómicas de grado 3, para dos dimensiones")
imprimirTabla(p)

Tensor de entrada
[[0.79386845]
 [0.77497133]
 [0.90420326]
 [0.34969623]
 [0.07814349]]
Características polinómicas de grado 3, para una dimensión


Tensor de entrada
[[0.3602924  0.94460525]
 [0.89025894 0.48088   ]
 [0.87353763 0.88311864]
 [0.719444   0.31751354]
 [0.42812284 0.68334476]]
Características polinómicas de grado 3, para dos dimensiones


Tensor de entrada
[[0.03695074 0.91348815 0.93060898]
 [0.36570744 0.87316652 0.59010237]
 [0.73047841 0.15610629 0.90863581]
 [0.708895   0.91711378 0.65266474]
 [0.03999489 0.04934272 0.55943072]]
Características polinómicas de grado 3, para dos dimensiones


## Conclusiones
La dimensiones hacen que los algoritmos de aprendizaje automático requieran de técnicas adicionales para disminuir el tiempo de procesamiento.
Uno de los algoritmos que vimos en clase (k vecinos) se ve afectado por la dimensionalidad, ya que los vecinos más cercanos se irán alejando conforme crezcan las dimensiones
Algunos métodos avanzados de estadística conocidos como Métodos de Montecarlo basados en cadenas de Markov ayudan a mitigar parcialmente este problema.
